#! /bin/sh

feh --bg-fill --randomize ~/Pictures/wp/*
bash /home/void/.config/polybar/launch.sh &

#workspaces-------------------------------------------
bspc monitor -d I II III IV V VI VII VIII IX X

#tiled-------------------------------------------
bspc config focus_follows_pointer true
bspc config border_width 1
bspc config window_gap   0
bspc config split_ratio  0.5
bspc config top_padding  28
bspc config click_to_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true

#monocle-------------------------------------------
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config paddingless_monocle  true

# Window Rules-------------------------------------------
bspc rule -a Firefox desktop=^1 follow=on
bspc rule -a Zathura state=tiled
bspc rule -a qBittorrent desktop=^10 state=floating
bspc rule -a URxvt:ncmpcpp follow=on desktop=^9 state=floating
