#! /bin/sh

nitrogen --restore
bash /home/void/.config/polybar/launch.sh &

wmname LG3D &


#workspaces-------------------------------------------
bspc monitor -d I II III IV V VI VII VIII IX X

#tiled-------------------------------------------
bspc config focus_follows_pointer true
bspc config border_width 2
bspc config focused_border_color "#C678DD"
bspc config window_gap   0
bspc config split_ratio  0.4
bspc config automatic_scheme alternate
bspc config top_padding  28
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config click_to_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true

#monocle-------------------------------------------
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true

# Window Rules-------------------------------------------
bspc rule -a firefox-default desktop=^1 follow=on
bspc rule -a Firefox desktop=^1 follow=on
bspc rule -a Zathura state=tiled
bspc rule -a qBittorrent desktop=^10 
#bspc rule -a Joplin desktop=^7 
bspc rule -a Alacritty:ncmpcpp state=floating  rectangle=600x500+383+134
bspc rule -a Nitrogen state=floating  rectangle=610x500+370+134
bspc rule -a android-studio state=floating border=off follow=on
